### ISSUE TITLE
Add program to find mean, median, mode of a array

### ISSUE THREAD

**Issue by AkMo3** [AkMo3/DSA-Java#46]

**Comment by KostasThan** [comment]
May i try this?

**Comment by AkMo3** [comment]
> 
> 
> May i try this?

Sure

**Comment by KostasThan** [comment]
May i ask for some clarifications:
 1. What should i return If there is more than one mode?
 2. As for the structure should i create a new class under algorithms or?

**Comment by AkMo3** [comment]
1. Right now return an array of all modes in sorted manner. Modes should occur only once in the array.
2. Add these programs in NumberSystem Directory, as these programs works around NumberSystems.

**Comment by KostasThan** [comment]
I think that with Generics we can find the mode in any Comparable<E> type array. You want me to try this or just stick to int and double? And if so, the classes should still be under the NumberSystem package?

**Comment by AkMo3** [comment]
Yup. Generic will be prefered always. And if you are implementing Generic add it in Misc.

**Comment by AkMo3** [comment]
Ping. What`s the status

**Comment by KostasThan** [comment]
I got an exam ahead of me in Tuesday,and i am running a little late. I will be done with the Median tomorrow though. Sorry for the delay.

**Comment by AkMo3** [comment]
No problem man. Focus on exams first xD

**Comment by KostasThan** [comment]
Hey, about the Mode class, there are two available options?

1.  Support only double and int,resulting in O(n) space complexity and O(n) time complexity.
2. Support every comparable type, having to use HashMaps and maybe ArrayList, and a complexity of time O(nlogn)

What would you like me to do?
Have a nice Sunday.

**Comment by AkMo3** [comment]
I would prefer to go with first one. Same to you brother.

**Comment by KostasThan** [comment]
Hey, 
Thanks for your patience. I am done with the Mode, with one issue though. 

Turns out 
> Support only double and int,resulting in O(n) space complexity and O(n) time complexity.

can only happen if we know the max and the min element. 
For me to find them only adds on top of the said complexity.

With that said i went on the second approach:

-  made it quite clear on how the algorithm,placing comments where need be
 - and the logic is fewer that 20 lines of code. 

But 😅 ,Java does not let you to create a new generic array so currently I
return a list,ordered as you pointed out. Should I commit that or find another way?

Below is an example:
![image](https://user-images.githubusercontent.com/36800742/101509012-fb523d00-3980-11eb-8223-291b71779843.png)

PS1: I will change the package to misc, should you accept it, since its the generic type
PS2: I **will** add comments and javadoc. 
PS3: Again, thanks for being so kind and patient!

**Comment by AkMo3** [comment]
No, issues you can continue with it.
